version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cattrs
    versions:
    - ">= 1.1.a, < 1.2"
  - dependency-name: cloudpickle
    versions:
    - ">= 1.5.a, < 1.6"
  - dependency-name: google-cloud-bigquery
    versions:
    - ">= 2.4.a, < 2.5"
  - dependency-name: spacy
    versions:
    - ">= 2.3.a, < 2.4"
  - dependency-name: pylint
    versions:
    - 2.7.1
    - 2.8.1
  - dependency-name: google-cloud-bigquery
    versions:
    - 2.10.0
    - 2.11.0
    - 2.12.0
    - 2.13.0
    - 2.13.1
    - 2.7.0
    - 2.8.0
    - 2.9.0
  - dependency-name: pyarrow
    versions:
    - 3.0.0
  - dependency-name: cattrs
    versions:
    - 1.2.0
    - 1.3.0
    - 1.4.0
    - 1.5.0
  - dependency-name: apache-airflow[crypto,jdbc,postgres]
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: spacy
    versions:
    - 3.0.0
    - 3.0.1
    - 3.0.3
    - 3.0.4
    - 3.0.5
  - dependency-name: boto3
    versions:
    - 1.17.16
  - dependency-name: pip
    versions:
    - "21.0"
    - 21.0.1
