version: '3.4'

x-pipeline-env:
    &pipeline-env
        - DEPLOYMENT_ENV=${PEERSCOUT_DAGS_DEPLOYMENT_ENV}
        - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/credentials.json
        - EXTRACT_KEYWORDS_FILE_PATH=/peerscout/app-config/peerscout-keyword/peerscout-keyword-data-pipeline.config.yaml
        - EXTRACT_KEYWORDS_MAX_ROWS=${EXTRACT_KEYWORDS_MAX_ROWS}

x-pipeline-volumes:
    &pipeline-volumes
        - ${GOOGLE_APPLICATION_CREDENTIALS:-~/.config/gcloud/application_default_credentials.json}:/root/.config/gcloud/credentials.json
        - ~/.aws/credentials:/root/.aws/credentials
        - ./test-config/peerscout-keyword-extraction-data-pipeline.config.yaml:/peerscout/app-config/peerscout-keyword/peerscout-keyword-data-pipeline.config.yaml

x-pipeline-defaults:
    &pipeline-defaults
        volumes: *pipeline-volumes
        environment: *pipeline-env

services:
    peerscout-dags:
        environment:
            GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/credentials.json
        volumes:
            - ./credentials.json:/root/.config/gcloud/credentials.json
        build:
            context: .
        image: ${IMAGE_REPO}:${IMAGE_TAG}
        command: ''

    peerscout-dags-dev:
        environment:
            - DEPLOYMENT_ENV=ci
        volumes:
            - ./credentials.json:/root/.config/gcloud/credentials.json
        build:
            context: .
            dockerfile: Dockerfile
            args:
                install_dev: y
        image:  ${IMAGE_REPO}-dev:${IMAGE_TAG}
        command: /bin/sh -c exit 0
        entrypoint: []

    test-client:
        image:  ${IMAGE_REPO}-dev:${IMAGE_TAG}
        environment: *pipeline-env
        volumes: *pipeline-volumes
        command: >
            bash -c "./run_test.sh with-end-to-end"

    data-hub-pipelines:
        <<: *pipeline-defaults
        image:  ${IMAGE_REPO}-dev:${IMAGE_TAG}
        environment:
            - DEPLOYMENT_ENV=${PEERSCOUT_DAGS_DEPLOYMENT_ENV}
            - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/credentials.json
            - AWS_CONFIG_FILE=/root/.aws/credentials
            - EXTRACT_KEYWORDS_FILE_PATH=/peerscout/app-config/peerscout-keyword/peerscout-keyword-data-pipeline.config.yaml
            - EXTRACT_KEYWORDS_MAX_ROWS=${EXTRACT_KEYWORDS_MAX_ROWS}
        user: 0:0
