version: '3.4'

x-pipeline-volumes:
    &pipeline-volumes
      - ~/.config/gcloud/application_default_credentials.json:/tmp/credentials.json
      - ~/.aws/credentials:/tmp/.aws-credentials
      - ./peerscout:/home/airflow/peerscout
      - ${PEERSCOUT_DAGS_CONFIG:-./test-config/peerscout-keyword-extraction-data-pipeline.config.yaml}:/home/airflow/app-config/peerscout-keyword/peerscout-keyword-data-pipeline.config.yaml

services:
    data-hub-pipelines:
        volumes: *pipeline-volumes
